apiVersion: v1
kind: ServiceAccount
metadata:
  name: wso2svc-account
  namespace : wso2

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2apim-deployment
  namespace: wso2
spec:
  selector:
    matchLabels:
      deployment: wso2apim
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: wso2apim
    spec:
      containers:
      - name: wso2apim
        image: wso2/wso2am:2.6.0
        # probe definitions
        livenessProbe:
          httpGet:
            path: /carbon
            port: 9443
            scheme: HTTPS
          initialDelaySeconds: 180
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /carbon
            port: 9443
            scheme: HTTPS
          initialDelaySeconds: 180
          failureThreshold: 3
          periodSeconds: 10
        lifecycle:
          preStop:
            exec:
              command:  ['sh', '-c', '${WSO2_SERVER_HOME}/bin/wso2server.sh stop']
        resources:
          requests:
            memory: 2Gi
            cpu: 2000m
          limits:
            memory: 3Gi
            cpu: 3000m
        securityContext:
          runAsUser: 802
        ports:
        -
          containerPort: 8280
          protocol: "TCP"
        -
          containerPort: 8243
          protocol: "TCP"
        -
          containerPort: 9763
          protocol: "TCP"
        -
          containerPort: 9443
          protocol: "TCP"
        volumeMounts:
        - name: apim-conf
          mountPath: /home/wso2carbon/wso2-config-volume/repository/conf
      serviceAccountName: wso2svc-account
      volumes:
      - name: apim-conf
        configMap:
          name: apim-conf

---

apiVersion: v1
kind: Service
metadata:
  name: wso2apim-service
  namespace: wso2
spec:
  # label keys and values that must match in order to receive traffic for this service
  selector:
    deployment: wso2apim
  ports:
    # ports that this service should serve on
    -
      name: pass-through-http
      protocol: TCP
      port: 8280
    -
      name: pass-through-https
      protocol: TCP
      port: 8243
    -
      name: servlet-http
      protocol: TCP
      port: 9763
    -
      name: servlet-https
      protocol: TCP
      port: 9443
